### ISSUE TITLE
line 17: mapping key "restart" already defined at line 14

### ISSUE THREAD

**Issue by janniksam** [multiversx/mx-multi-factor-auth-go-service#141]
Is it just me or is the docker-compose file having some issues?
There is "restart" defined twice, is this a mistake? "Always" and "No" 😆 It does seem to be not work anymore in newer versions of docker-compose (Docker Compose version v2.27.0-desktop.2).

![image](https://github.com/multiversx/mx-multi-factor-auth-go-service/assets/15337798/724af79e-114a-456a-983d-e4b88b1afff2)

**Comment by ssd04** [comment]
yes, that was a mistake, thanks for the catch

**Comment by ssd04** [comment]
fixed here https://github.com/multiversx/mx-multi-factor-auth-go-service/pull/142
